name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - name: Begin CD...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use GoLang 1.17
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.8"

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm t

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: new wasm release

      - name: Setup npm profile
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          # Gives a clean failure prior to attempting a release if npm token is incorrect
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git profile
        run: |
          git config user.name "Transmute CD"
          git config user.email "engineers@transmute.industries"

      - name: Publish to npm
        run: npm run publish:unstable
