name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use GoLang 14
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.8"

      - name: Install
        run: npm i

      - name: TEST WASM
        run: ./scripts/make-wasm.sh

      - name: Test
        run: npm t
